apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gateway
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: viktor@farcic.com
    privateKeySecretRef:
      name: letsencrypt-gateway
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: main
            namespace: gateway
            kind: Gateway
