apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://projectcontour.github.io/helm-charts
    chart: contour
    targetRevision: 0.2.1
    helm:
      valuesObject:
        gatewayAPI:
          manageCRDs: true
        configInline:
          gateway:
            gatewayRef:
              name: main
              namespace: gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
