apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-gcp
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    iam.gke.io/gcp-service-account: crossplane@vfarcic.iam.gserviceaccount.com
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-certificatemanager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: crossplane-provider-gcp
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-certificatemanager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-certificatemanager:v2.4.0
  runtimeConfigRef:
    name: provider-gcp-certificatemanager
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: gcp-certificatemanager-namespaced
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  providerRef:
    name: provider-gcp-certificatemanager
  matchManagedResourceDefinitions:
    - group: certificatemanager.gcp.m.upbound.io
      resources:
        - certificates
        - certificatemaps
        - certificatemapentries
