apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  projectID: vfarcic
  credentials:
    source: InjectedIdentity
---
apiVersion: certificatemanager.gcp.m.upbound.io/v1beta1
kind: Certificate
metadata:
  name: jaeger-certificate
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  forProvider:
    location: global
    managed:
      - domains:
          - jaeger.devopstoolkit.ai
  providerConfigRef:
    name: default
---
apiVersion: certificatemanager.gcp.m.upbound.io/v1beta2
kind: CertificateMapEntry
metadata:
  name: jaeger-map-entry
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  forProvider:
    certificatesRefs:
      - name: jaeger-certificate
    hostname: jaeger.devopstoolkit.ai
    map: devopstoolkit-map
  providerConfigRef:
    name: default
