apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 2.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: crossplane-vpa
  namespace: crossplane-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crossplane
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: crossplane-rbac-manager-vpa
  namespace: crossplane-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crossplane-rbac-manager
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
