apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dot-ai-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/vfarcic/dot-ai-controller/charts
    chart: dot-ai-controller
    targetRevision: 0.34.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dot-ai
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
