apiVersion: dot-ai.devopstoolkit.live/v1alpha1
kind: RemediationPolicy
metadata:
  name: warning-events-slack
  namespace: dot-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  mcpEndpoint: http://dot-ai.dot-ai.svc.cluster.local:3456/api/v1/tools/remediate
  mcpAuthSecretRef:
    name: dot-ai-secrets
    key: auth-token
  mode: manual
  eventSelectors:
    - type: Warning
      namespace: argocd
    - type: Warning
      namespace: cert-manager
    - type: Warning
      namespace: dot-ai
    - type: Warning
      namespace: examples
    - type: Warning
      namespace: infra
    - type: Warning
      namespace: traefik
  notifications:
    slack:
      enabled: true
      channel: "#dot-ai-tests"
      webhookUrlSecretRef:
        name: dot-ai-secrets
        key: SLACK_WEBHOOK_URL
      notifyOnStart: true
      notifyOnComplete: true
  rateLimiting:
    eventsPerMinute: 15
    cooldownMinutes: 60
---
apiVersion: dot-ai.devopstoolkit.live/v1alpha1
kind: GitKnowledgeSource
metadata:
  name: devops-catalog
  namespace: dot-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  repository:
    url: https://github.com/vfarcic/devops-catalog.git
    branch: main
    depth: 1
    secretRef:
      name: dot-ai-secrets
      key: github-token
  paths:
    - "**/*.md"
  schedule: "@every 24h"
  mcpServer:
    url: http://dot-ai.dot-ai.svc.cluster.local:3456
    authSecretRef:
      name: dot-ai-secrets
      key: auth-token
  metadata:
    source: devops-catalog
  deletionPolicy: Delete