apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dot-ai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/vfarcic/dot-ai/charts
    chart: dot-ai
    targetRevision: 0.172.0
    helm:
      valuesObject:
        ai:
          provider: anthropic_haiku
        ingress:
          enabled: false
        controller:
          enabled: true
        extraEnv:
          - name: DOT_AI_USER_PROMPTS_REPO
            value: "https://github.com/vfarcic/dot-ai"
          - name: DOT_AI_USER_PROMPTS_PATH
            value: "user-prompts"
  destination:
    server: https://kubernetes.default.svc
    namespace: dot-ai
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
