apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: dot-ai
  namespace: dot-ai
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: dot-ai
