apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: vfarcic
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            namespace: external-secrets
            key: key.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dot-ai-secrets
  namespace: dot-ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: dot-ai-secrets
    creationPolicy: Owner
  data:
    - secretKey: anthropic-api-key
      remoteRef:
        key: anthropic-api-key
    - secretKey: openai-api-key
      remoteRef:
        key: openai-key
    - secretKey: auth-token
      remoteRef:
        key: dot-ai-auth-token
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: slack-webhook-url
