apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 4.3.4
    helm:
      valuesObject:
        allInOne:
          enabled: true
        provisionDataStore:
          cassandra: false
        storage:
          type: memory
        collector:
          enabled: false
        query:
          enabled: false
        agent:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: jaeger
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jaeger
  namespace: jaeger
spec:
  parentRefs:
    - name: main
      namespace: gateway
      sectionName: https
  hostnames:
    - jaeger.devopstoolkit.ai
  rules:
    - backendRefs:
        - name: jaeger
          port: 16686
