apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.3.4
    helm:
      valuesObject:
        reportsController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-admission-controller-vpa
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-admission-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-background-controller-vpa
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-background-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-cleanup-controller-vpa
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-cleanup-controller
  updatePolicy:
    updateMode: "Off"
