apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: port-credentials
  namespace: port-k8s-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: port-credentials
    creationPolicy: Owner
  data:
    - secretKey: PORT_CLIENT_ID
      remoteRef:
        key: port-client-id
    - secretKey: PORT_CLIENT_SECRET
      remoteRef:
        key: port-client-secret
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: port-k8s-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://port-labs.github.io/helm-charts
    chart: port-k8s-exporter
    targetRevision: "*"
    helm:
      valuesObject:
        secret:
          useExistingSecret: true
          name: port-credentials
        portBaseUrl: https://api.port.io
        stateKey: dot-ai
        eventListener:
          type: POLLING
        extraEnv:
          - name: CLUSTER_NAME
            value: dot-ai
        configMap:
          config: |
            createMissingRelatedEntities: true
            resources:
              # Namespaces
              - kind: v1/namespaces
                selector:
                  query: .metadata.name | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"namespace"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          labels: .metadata.labels
                        relations:
                          Cluster: env.CLUSTER_NAME
              # Cluster
              - kind: v1/namespaces
                selector:
                  query: .metadata.name | contains("kube-system")
                port:
                  entity:
                    mappings:
                      - identifier: env.CLUSTER_NAME
                        title: env.CLUSTER_NAME
                        blueprint: '"cluster"'
              # Deployments
              - kind: apps/v1/deployments
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-Deployment-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"workload"'
                        icon: '"Deployment"'
                        properties:
                          kind: '"Deployment"'
                          creationTimestamp: .metadata.creationTimestamp
                          replicas: .spec.replicas
                          availableReplicas: .status.availableReplicas
                          labels: .metadata.labels
                          containers: (.spec.template.spec.containers | map({name, image, resources}))
                          strategy: .spec.strategy.type
                          hasLatest: .spec.template.spec.containers[].image | contains(":latest")
                          hasLimits: .spec.template.spec.containers | all(has("resources") and (.resources.limits.memory and .resources.limits.cpu))
                          isHealthy: if .spec.replicas == .status.availableReplicas then "Healthy" else "Unhealthy" end
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # DaemonSets
              - kind: apps/v1/daemonsets
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-DaemonSet-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"workload"'
                        icon: '"Cluster"'
                        properties:
                          kind: '"DaemonSet"'
                          creationTimestamp: .metadata.creationTimestamp
                          labels: .metadata.labels
                          containers: (.spec.template.spec.containers | map({name, image, resources}))
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # StatefulSets
              - kind: apps/v1/statefulsets
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-StatefulSet-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"workload"'
                        icon: '"Cluster"'
                        properties:
                          kind: '"StatefulSet"'
                          creationTimestamp: .metadata.creationTimestamp
                          replicas: .spec.replicas
                          availableReplicas: .status.availableReplicas
                          labels: .metadata.labels
                          containers: (.spec.template.spec.containers | map({name, image, resources}))
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # ReplicaSets
              - kind: apps/v1/replicasets
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"replicaset"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          replicas: .spec.replicas
                          availableReplicas: .status.availableReplicas
                          readyReplicas: .status.readyReplicas
                          labels: .metadata.labels
                          selector: .spec.selector
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
                          Workload: .metadata.ownerReferences[0].name + "-Deployment-" + .metadata.namespace + "-" + env.CLUSTER_NAME
              # Pods
              - kind: v1/pods
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"pod"'
                        properties:
                          phase: .status.phase
                          node: .spec.nodeName
                          startTime: .status.startTime
                          creationTimestamp: .metadata.creationTimestamp
                          labels: .metadata.labels
                          containers: (.spec.containers | map({name, image}))
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
                          Workload: .metadata.ownerReferences[0].name as $owner | if .metadata.ownerReferences[0].kind == "ReplicaSet" then null else ($owner + "-" + .metadata.ownerReferences[0].kind + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME) end
              # Services
              - kind: v1/services
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"service"'
                        properties:
                          type: .spec.type
                          clusterIP: .spec.clusterIP
                          ports: .spec.ports
                          selector: .spec.selector
                          labels: .metadata.labels
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Ingresses
              - kind: networking.k8s.io/v1/ingresses
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"ingress"'
                        properties:
                          ingressClassName: .spec.ingressClassName
                          hosts: "[.spec.rules[].host]"
                          rules: .spec.rules
                          tls: .spec.tls
                          labels: .metadata.labels
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Gateway API - Gateways
              - kind: gateway.networking.k8s.io/v1/gateways
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"gateway"'
                        properties:
                          gatewayClassName: .spec.gatewayClassName
                          listeners: .spec.listeners
                          addresses: .status.addresses
                          labels: .metadata.labels
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Gateway API - HTTPRoutes
              - kind: gateway.networking.k8s.io/v1/httproutes
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"httproute"'
                        properties:
                          hostnames: .spec.hostnames
                          parentRefs: .spec.parentRefs
                          rules: .spec.rules
                          labels: .metadata.labels
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
                          Gateway: "[.spec.parentRefs[] | .name + \"-\" + (.namespace // .metadata.namespace) + \"-\" + env.CLUSTER_NAME]"
              # CapabilityScanConfig CRD
              - kind: dot-ai.devopstoolkit.live/v1alpha1/capabilityscanconfigs
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"capabilityscanconfig"'
                        properties:
                          debounceWindowSeconds: .spec.debounceWindowSeconds
                          mcpEndpoint: .spec.mcp.endpoint
                          mcpCollection: .spec.mcp.collection
                          mcpAuthSecretRef: .spec.mcp.authSecretRef
                          lastScanTime: .status.lastScanTime
                          ready: .status.conditions[] | select(.type == "Ready") | .status == "True"
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # RemediationPolicy CRD
              - kind: dot-ai.devopstoolkit.live/v1alpha1/remediationpolicies
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"remediationpolicy"'
                        properties:
                          mode: .spec.mode
                          eventSelectors: .spec.eventSelectors
                          mcpEndpoint: .spec.mcpEndpoint
                          mcpTool: .spec.mcpTool
                          confidenceThreshold: .spec.confidenceThreshold
                          maxRiskLevel: .spec.maxRiskLevel
                          rateLimiting: .spec.rateLimiting
                          notifications: .spec.notifications
                          ready: .status.conditions[] | select(.type == "Ready") | .status == "True"
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # ResourceSyncConfig CRD
              - kind: dot-ai.devopstoolkit.live/v1alpha1/resourcesyncconfigs
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"resourcesyncconfig"'
                        properties:
                          debounceWindowSeconds: .spec.debounceWindowSeconds
                          resyncIntervalMinutes: .spec.resyncIntervalMinutes
                          mcpEndpoint: .spec.mcpEndpoint
                          mcpAuthSecretRef: .spec.mcpAuthSecretRef
                          active: .status.active
                          watchedResourceTypes: .status.watchedResourceTypes
                          totalResourcesSynced: .status.totalResourcesSynced
                          syncErrors: .status.syncErrors
                          lastSyncTime: .status.lastSyncTime
                          lastResyncTime: .status.lastResyncTime
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              # Solution CRD
              - kind: dot-ai.devopstoolkit.live/v1alpha1/solutions
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"solution"'
                        properties:
                          intent: .spec.intent
                          context: .spec.context
                          resources: .spec.resources
                          labels: .metadata.labels
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          Namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
  destination:
    server: https://kubernetes.default.svc
    namespace: port-k8s-exporter
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
